clients/urls.py
from django.urls import path

from . import views
from .views import AddClientView, ClientDeleteView, ClientUpdateView, ListClientsView

app_name = "clients"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("clients/", ListClientsView.as_view(), name="client_list"),
    path("create/", AddClientView.as_view(), name="client_create"),
    path("update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="c")),
    path("mailings/", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
    path("mail_messages/", include("mail_messages.urls", namespace="mail_messages")),
    path("attempt/", include("attempt.urls", namespace="attempt")),
    path("accounts/", include("allauth.urls")),
    path("", include("clients.urls", namespace="clients")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from . import views

app_name = "mailings"

urlpatterns = [
    path("mailings/", views.MailingListView.as_view(), name="mailing_list"),
    path("mailings/create/", views.MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailings/<int:pk>/update/",
        views.MailingUpdateView.as_view(),
        name="mailing_update",
    ),
    path(
        "mailings/<int:pk>/delete/",
        views.MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path(
        "mailings/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_detail"
    ),
    path(
        "mailings/<int:pk>/deactivate/",
        views.MailingDeactivateView.as_view(),
        name="mailing_deactivate",
    ),
    path("send_mailing/", views.send_mailing, name="send_mailing"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .forms import LoginForm
from .views import (
    CustomPasswordResetConfirmView,
    CustomPasswordResetForm,
    LoginView,
    LogoutView,
    RegisterView,
    UserBlockView,
    UserListView,
    UserUnlockView,
    VerifyEmailView,
)

app_name = "users"


urlpatterns = [
    # Регистрация/авторизация
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("verify/<str:token>/", VerifyEmailView.as_view(), name="verify-email"),
    # Сброс пароля
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            form_class=CustomPasswordResetForm,
            template_name="users/registration/password_reset.html",
            success_url=reverse_lazy("users:password_reset_done"),
            email_template_name="users/registration/password_reset_email.html",
            subject_template_name="users/registration/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(
            template_name="users/registration/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # Блокировка
    path("block/<int:pk>/", UserBlockView.as_view(), name="block_user"),
    path("unblock/<int:pk>/", UserUnlockView.as_view(), name="unblock_user"),
    path("users/", UserListView.as_view(), name="user_list"),
]

clients/models.py
from django.conf import settings
from django.db import models


class Client(models.Model):
    "Модель получатель рассылки"

    email = models.EmailField(unique=True, db_index=True)
    full_name = models.CharField(
        max_length=100, verbose_name="Ф.И.О", null=False, blank=False
    )
    comment = models.TextField(verbose_name="Комментарий", null=True, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        null=False,
    )

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ("email",)
        permissions = [
            ("can_view_client", "Can view client"),
        ]

clients/forms.py
from django import forms

from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["email", "full_name", "comment"]
        widgets = {
            "comment": forms.Textarea(
                attrs={"rows": 4, "placeholder": "Введите дополнительную информацию"}
            ),
        }
        help_texts = {"comment": "Введите дополнительную информацию о получателе"}

    def clean(self):
        cleaned_data = super(ClientForm, self).clean()
        email = cleaned_data.get("email")
        full_name = cleaned_data.get("full_name")

        if not email:
            raise forms.ValidationError("Поле Email обязательно для заполнения")
        if not full_name:
            raise forms.ValidationError("Поле ФИО обязательно для заполнения")

        if email:
            owner = self.instance.owner if self.instance.pk else None
            if (
                owner is not None
                and Client.objects.filter(email=email, owner=owner).exists()
            ):
                raise forms.ValidationError(
                    "Этот email уже используется другим получателем"
                )

        return cleaned_data

clients/views.py
from django.http import request, HttpResponseForbidden, HttpResponseRedirect
from functools import wraps
from allauth.core.internal.httpkit import redirect
from django.contrib.auth import get_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    TemplateView,
    UpdateView,
)
from rest_framework.generics import get_object_or_404
from rest_framework.reverse import reverse_lazy, reverse

from mail_messages.utils import is_manager
from mailings.services import get_mailing_statistics

from .forms import ClientForm
from .models import Client


class HomeView(TemplateView):
    template_name = "clients/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            if is_manager(self.request.user):
                statistics = get_mailing_statistics()
            else:
                statistics = get_mailing_statistics(self.request.user)

            context["count_mailings"] = statistics["total_mailings"]
            context["count_active_mailings"] = statistics["active_mailings"]
            context["unique_contacts"] = statistics["unique_clients"]
        else:
            context["count_mailings"] = 0
            context["count_active_mailings"] = 0
            context["unique_contacts"] = 0
        return context


class AddClientView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = "clients/client_create.html"
    success_url = reverse_lazy("clients:client_list")

    def form_valid(self, form):
        """Присваиваем авторизованного пользователя создаваемому клиенту"""
        user = get_user(self.request)
        form.instance.owner = user
        form.instance.save()
        return super().form_valid(form)


class ListClientsView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "clients/client_list.html"
    context_object_name = "clients"

    @method_decorator(cache_page(60 * 5))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.request.user.groups.filter(name="Managers").exists():
            return Client.objects.all()
        return Client.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_manager"] = self.request.user.groups.filter(
            name="Managers"
        ).exists()
        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "clients/client_update.html"
    success_url = reverse_lazy("clients:client_list")
    context_object_name = "client"

    def get_object(self, queryset=None):
        client = get_object_or_404(Client, pk=self.kwargs.get("pk"))
        if client.owner is None:
            raise PermissionDenied("У этого получателя не установлен владелец.")
        if is_manager(self.request.user) and client.owner != self.request.user:
            raise PermissionDenied(
                "Менеджеры не имеют прав на редактирование чужих получателей"
            )
        if not is_manager(self.request.user) and client.owner != self.request.user:
            raise PermissionDenied("У вас нет прав на редактирование этого получателя")
        return client

    def form_valid(self, form):
        form.instance.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = "clients/client_delete.html"
    success_url = reverse_lazy("clients:clients_list")

    def get_object(self, queryset=None):
        client = get_object_or_404(Client, pk=self.kwargs.get("pk"))
        if not is_manager(self.request.user) and client.owner != self.request.user:
            raise PermissionDenied("У вас нет прав на удаление этого получателя")
        if is_manager(self.request.user) and client.owner != self.request.user:
            raise PermissionDenied("Менеджеры не могут удалять чужих получателей")
        return client

clients/templates/clients/add_client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

clients/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Управление рассылками{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    {% include "clients/headers.html" %}
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    {% include "clients/footer.html" %}
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

clients/templates/clients/client_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

clients/templates/clients/client_create.html
{% extends 'clients/base.html' %}

{% block title %}Добавить получателя{% endblock %}

{% block content %}
<h1>Добавить получателя</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>
<a href="{% url 'clients:client_list' %}" class="btn btn-secondary">Назад</a>
{% endblock %}

clients/templates/clients/client_delete.html
{% extends 'clients/base.html' %}

{% block title %}Удалить получателя{% endblock %}

{% block content %}
<h1>Удалить клиента</h1>
<p>Вы уверены, что хотите удалить получателя? {{ client }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
</form>
<a href="{% url 'clients:client_list' %}" class="btn btn-secondary">Отмена</a>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'clients/base.html' %}

{% block title %}
    Детальная информация о получателе
{% endblock %}

{% block content %}
    <div class="container my-5">
        <h2 class="text-center my-3">ФИО: {{object.full_name }}</h2>
        <p class="text-center">Электронная почта: {{object.email}}</p>
        <p class="text-center">Комментарий: {{object.comment}}</p>
        <div class="text-center">
            <a href="{% url 'clients:client_update' client.pk %}" class="btn btn-lg btn-block btn-outline-primary mt-3">Редактировать</a>
            <a href="{% url 'clients:client_delete' client.pk %}" class="btn btn-lg btn-block btn-outline-primary mt-3">Удалить</a>
            <a href="{% url 'clients:client_list' %}" class="btn btn-lg btn-primary mt-3">Назад</a>
        </div>
    </div>
{% endblock %}

clients/templates/clients/client_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

clients/templates/clients/client_list.html
{% extends 'clients/base.html' %}

{% block title %}Список получателей рассылок{% endblock %}

{% block content %}
<h1>Список клиентов</h1>
<a href="{% url 'clients:client_create' %}" class="btn btn-primary">Добавить получателя</a>

<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>ФИО</th>
            <th>Комментарий</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
        <tr>
            <td>{{ client.email }}</td>
            <td>{{ client.full_name }}</td>
            <td>{{ client.comment }}</td>
            <td>
                <a href="{% url 'clients:client_update' client.pk %}" class="btn btn-warning">Редактировать</a>
                <a href="{% url 'clients:client_delete' client.pk %}" class="btn btn-danger">Удалить</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">Нет доступных клиентов.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

clients/templates/clients/client_update.html
{% extends 'clients/base.html' %}

{% block title %}Редактировать получателя{% endblock %}

{% block content %}
<h1>Редактировать получателя</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Сохранить изменения</button>
</form>
<a href="{% url 'clients:client_list' %}" class="btn btn-secondary">Назад</a>
{% endblock %}

clients/templates/clients/footer.html
<footer class="pt-3 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <h5>Рассылка</h5>
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Рассылка</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

clients/templates/clients/headers.html
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Рассылка</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'clients:home' %}">Главная</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Рассылка
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/mailings/mailings/">Список рассылки</a></li>
              <li><a class="dropdown-item" href="/mail_messages/">Список писем</a></li>
              <li><a class="dropdown-item" href="/clients/">Список пользователей</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="">Статистика</a></li>
            </ul>
          </li>
        </ul>
        <div class="d-flex align-items-center">
          {% if user.is_active %}
            <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
          {% csrf_token %}
            <a href="{% url 'users:login' %}""><button class="p-2 btn btn-outline-primary" type="submit">Выйти</button></a>
            </form>
          {% else %}
            <a href="{% url 'users:login' %}"><button class="p-2 btn btn-outline-primary" type="submit">Войти</button></a>
            <a href="{% url 'users:register' %}"><button class="p-2 btn btn-outline-primary" type="submit">Регистрация</button></a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

clients/templates/clients/home.html
{% extends 'clients/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Статистика рассылок</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <strong>Количество всех рассылок:</strong> {{ total_mailings }}
                        </li>
                        <li class="list-group-item">
                            <strong>Количество активных рассылок:</strong> {{ active_mailings }}
                        </li>
                        <li class="list-group-item">
                            <strong>Количество уникальных клиентов:</strong> {{ clients }}
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Список рассылок</h5>
                    <ul class="list-group list-group-flush">
                        {% for mailing in mailings %}
                            <li class="list-group-item">
                                <a href="{% url 'mailings:mailing_detail' mailing.pk %}">{{ mailing.name }}</a>
                            </li>
                        {% empty %}
                            <li class="list-group-item">Нет рассылок.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}